name: 'Flutter prepare action'
description: 'Get Flutter SDK and get ready to build'
inputs:
  flutter-version:
    description: 'Flutter version'
    required: true
  format-exits-if-changed:
    description: 'Set exit code to 1 if there are formatting issues'
    required: false
    default: false
  github-token:
    description: 'The GitHub token to upload the code coverage report'
    required: true
runs:
  using: "composite"
  steps:
    # Get Flutter SDK
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: stable

    - name: Flutter vesion
      run: flutter --version
      shell: bash

    - name: Install dependencies
      run: flutter pub get
      shell: bash

    - name: Format code (exit)
      if: inputs.format-exits-if-changed == 'true'
      run: dart format --line-length=80 --set-exit-if-changed .
      shell: bash

    - name: Format code (no exit)
      if: inputs.format-exits-if-changed == 'false'
      run: dart format --line-length=80 .
      shell: bash

    - name: Analyze code
      run: flutter analyze
      shell: bash

    - name: Run Tests
      run: flutter test
      shell: bash
    
    - name: Run Flutter Tests
      run: flutter test --coverage
      shell: bash

    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1

    - name: Report Code Coverage
      uses: zgosalvez/github-actions-report-lcov@v4.1.6
      with:
        coverage-files: coverage/lcov.info
        minimum-coverage: 0
        artifact-name: code-coverage-report
        github-token: ${{ inputs.github-token }}
