name: 'Flutter prepare action'
description: 'Get Flutter SDK and get ready to build'
inputs:
  flutter-version:
    description: 'Flutter version'
    required: true
  format-exit-if-changed:
    description: 'Set exit code to 1 if there are formatting issues'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    # Get Flutter SDK
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: stable

    - name: Flutter vesion
      run: flutter --version
      shell: bash

    - name: Install dependencies
      run: flutter pub get
      shell: bash

    - name: Format code (exit)
      if: format-exit-if-changed == 'true'
      run: dart format --line-length=80 --set-exit-if-changed .
      shell: bash

    - name: Format code (no exit)
      if: format-exit-if-changed == 'false'
      run: dart format --line-length=80 .
      shell: bash

    - name: Analyze code
      run: flutter analyze
      shell: bash

    - name: Run Tests
      run: flutter test
      shell: bash
