name: 'Flutter prepare action'
description: 'Get Flutter SDK and get ready to build'
inputs:
  flutter-version:
    description: 'Flutter version'
    required: true
  format-exits-if-changed:
    description: 'Set exit code to 1 if there are formatting issues'
    required: false
    default: false
  github-token:
    description: 'The GitHub token to upload the code coverage report'
    required: true
  update-coverage-comment: 
    description: 'Update the coverage comment'
    required: true
    default: false
runs:
  using: "composite"
  steps:
    # Get Flutter SDK
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: stable

    - name: Flutter vesion
      run: flutter --version
      shell: bash

    - name: Install dependencies
      run: flutter pub get
      shell: bash

    - name: Format code (exit)
      if: inputs.format-exits-if-changed == 'true' && github.event_name == 'push'
      run: dart format --line-length=80 --set-exit-if-changed .
      shell: bash

    - name: Format code (no exit)
      if: inputs.format-exits-if-changed == 'false' && github.event_name == 'push'
      run: dart format --line-length=80 .
      shell: bash

    - name: Analyze code
      if: github.event_name == 'push'
      run: flutter analyze
      shell: bash

    - name: Run Tests
      if: github.event_name == 'push'
      run: flutter test
      shell: bash
    
    - name: Run Flutter Tests
      if: github.event_name == 'pull_request'
      run: flutter test --coverage
      shell: bash

    - name: Setup LCOV
      if: github.event_name == 'pull_request'
      uses: hrishikesh-kadam/setup-lcov@v1

    - name: Report Code Coverage
      if: github.event_name == 'pull_request'
      uses: zgosalvez/github-actions-report-lcov@v4.1.6
      with:
        coverage-files: coverage/lcov.info
        minimum-coverage: 0
        artifact-name: code-coverage-report
        github-token: ${{ inputs.github-token }}
        update-comment: ${{ inputs.update-coverage-comment }}
