name: 'Flutter prepare action'
description: 'Get Flutter SDK and get ready to build'
inputs:
  flutter-version:
    description: 'Flutter version'
    required: true
runs:
  using: "composite"
  steps:
    # Checkout this repo
    - uses: actions/checkout@v3

    # Get Flutter SDK
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.version }}
        channel: stable

    - run: flutter --version

    # Install dependencies
    - run: flutter pub get

    # check for issues with formatting
    - run: dart format --line-length=80 --set-exit-if-changed .

    # check for issues through static analysis
    - run: flutter analyze

    # Run tests
    - run: flutter test
