name: flutter_action
description: A GitHub Action written in dart.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

  
dependencies:
  dio: ^5.4.1

dev_dependencies:
  melos: ^6.1.0
  test: ^1.25.2
