on: [push, pull_request]

jobs:
  test_job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: checks
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if GITHUB_TOKEN is empty
        run: |
          if [[ -z "${{ secrets.GITHUB_TOKEN }}" ]]; then
            echo "GITHUB_TOKEN is empty"
            exit 1
          else
            echo "GITHUB_TOKEN is not empty"
          fi
        shell: bash
      - name: Executes flutter-prepare-action
        uses: ./ # Uses an action in the root directory
        id: fpa
        with:
          flutter-version: '3.19.2'
          format-exits-if-changed: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Executes flutter-prepare-action using Melos
        uses: ./ # Uses an action in the root directory
        id: fpa_melos
        with:
          flutter-version: '3.19.2'
          format-exits-if-changed: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-melos: true